document.querySelector(".circlea").onclick=function(){
    document.querySelector(".visible").classList.remove("visible");
    document.querySelector(".tomato").classList.add("visible");
}
document.querySelector(".circleb").onclick=function(){
    document.querySelector(".visible").classList.remove("visible");
    document.querySelector(".cucumber").classList.add("visible");
}
document.querySelector(".circlec").onclick=function(){
    document.querySelector(".visible").classList.remove("visible");
    document.querySelector(".carrot").classList.add("visible");
}
document.querySelector(".size-changer").onclick=function(){
    document.querySelector(".small").classList.remove("small").classlist.add("big")
    document.querySelector(".big").classList.remove("big").classList.add("small")
}