document.querySelector(".circlea").onclick=function(){
    document.querySelector(".visible").classList.remove("visible");
    document.querySelector(".tomato").classList.add("visible");
}
document.querySelector(".circleb").onclick=function(){
    document.querySelector(".visible").classList.remove("visible");
    document.querySelector(".cucumber").classList.add("visible");
}
document.querySelector(".circlec").onclick=function(){
    document.querySelector(".visible").classList.remove("visible");
    document.querySelector(".carrot").classList.add("visible");
}