document.querySelector(".circlea").onClick=function(){
    document.querySelector(".visible").classList.remove(".visible");
    document.querySelector(".tomato").classList.add(".visible");
}
document.querySelector(".circleb").onClick=function(){
    document.querySelector(".visible").classList.remove(".visible");
    document.querySelector(".cucumber").classList.add(".visible");
}
document.querySelector(".circlec").onClick=function(){
    document.querySelector(".visible").classList.remove(".visible");
    document.querySelector(".carrot").classList.add(".visible");
}